context:
  name: dimorphite-dl
  version: "2.0.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/dimorphite_dl-${{ version }}.tar.gz
  sha256: dc4d615536281088da2fdb6398be22dacb0a48a4ca68fc532470ab0174571de1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - rdkit

tests:
  - python:
      imports:
        - dimorphite_dl
      python_version: ${{ python_min }}.*
      # disable pip check because of the following error:
      # dimorphite-dl 1.3.2 requires rdkit-pypi, which is not installed.
      pip_check: false

about:
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: |
    Dimorphite-DL adds hydrogen atoms to molecular representations, as appropriate for a user-specified pH range. It is a fast, accurate, accessible, and modular open-source program for enumerating small-molecule ionization states.
  homepage: https://github.com/Sulstice/dimorphite_dl

extra:
  recipe-maintainers:
    - hadim
